### PR TITLE
Add CVAT Logo

### PR DESCRIPTION
**Pull request by tisonkun**
Let's wait for CVAT's confirm.

image

### CODE REVIEW

**Comment by jihuayu** [comment]
How are our icons ordered? 
Should they be ordered in the order of addition time or alphabetical order by company name?

**Comment by bsekachev** [comment]
Hello, thanks for contacting us. 
I believe simple logo would look nicer. Attached the logo in .svg/.png here for your convenience

cvat-logo

image

**Comment by tisonkun** [comment]
@jihuayu Good point! We have a `title` field for metadata now. Let's try to sort logos by this field alphabetically

**Review by git-hulk — APPROVED** [review]

**Comment by tisonkun** [comment]
Twitter link https://x.com/tison1096/status/1763483779073790296?s=46&t=rCbLrJSBayvO_CKE6XmYKQ if you'd share the news or comment more on the background and experience.

**Pull request merged**
