### PR TITLE
Update docusaurus.config.js to enable dark mode switch

### PR DESCRIPTION
**Pull request by asad-awadia**
Screenshot 2024-03-12 160504

### CODE REVIEW

**Review by git-hulk — APPROVED** [review]

**Comment by tisonkun** [comment]
I remember we ever banned it because the homepage would have a dirty look (style incompatible)?

**Comment by git-hulk** [comment]
image
@tisonkun Yes, but it looks good for now(from my personal perspective).

**Comment by PragmaTwice** [comment]
> image @tisonkun Yes, but it looks good for now(from my personal perspective).

Really good? I cannot understand. The home page looks really bad in dark mode:
- The banner is still in light mode.
- Buttons are still in light mode.
- Namespace icon has a white rectangular frame.

**Comment by PragmaTwice** [comment]
Sorry but we need a good overall solution of dark mode.

Not just enable the dark mode switch.

**Comment by asad-awadia** [comment]
>Sorry but we need a good overall solution of dark mode.

I will whip up an HLD for it :) 

Perfection is the enemy of good and things can be added incrementally 

But in all seriousness, the dark mode looks great for all pages  - homepage looks off because the assets aren't dark mode but I can't update those

**Comment by git-hulk** [comment]
> > image @tisonkun Yes, but it looks good for now(from my personal perspective).
> 
> Really good? I cannot understand your point. The home page looks really bad in dark mode:
> 
> * The banner is still in light mode.
> * Buttons are still in light mode.
> * Namespace icon has a white rectangular frame.

😭 Maybe I have a bad sense of web UI, so I think those inconsistent colors between them are good for me. So I just mentioned that's my perspective.

**Pull request closed without merging**
