### PR TITLE
Make last-updated more accurate

### PR DESCRIPTION
**Pull request by PragmaTwice**
image

"Last updated on ..." need more commit information.

### CODE REVIEW

**Comment by tisonkun** [comment]
@PragmaTwice can you attach screenshots to differ before and after?

**Comment by PragmaTwice** [comment]
Before, in every page it just show the last commit.

**Comment by PragmaTwice** [comment]
It is hard to reproduce, and the dev environment will hide these information.

**Review by tisonkun — APPROVED** [review]
Let's go :D

**Pull request merged**
