### PR TITLE
Fix typo in new kvrocks2redis doc

### PR DESCRIPTION
**Pull request by enjoy-binbin**

### CODE REVIEW

**Comment by enjoy-binbin** [comment]
i see in kvrocks2redis, we are useing this:
```
# If the source Kvrocks enabled the cluster mode, should enable it here as well.
# Default: no
cluster-enable no
```

and kvrocks is actually using cluster-enabled.

**Review by git-hulk — APPROVED** [review]
LGTM, thanks

**Comment by PragmaTwice** [comment]
> and kvrocks is actually using cluster-enabled.

Maybe we can rename it to `cluster-enabled`.

**Comment by git-hulk** [comment]
> > and kvrocks is actually using cluster-enabled.
> 
> Maybe we can rename it to `cluster-enabled`.

Added into the track issues

**Comment by enjoy-binbin** [comment]
since #1673 has been merged, when do we update the doc?
We haven't released a new version yet, so the new cluster-enabled does not working.

**Comment by git-hulk** [comment]
I think we can update the doc before releasing the new version, and tell them to use the unstable version if someone asked.

**Pull request merged**
